//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GlobalLending.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerService
    {
        public int ID { get; set; }
        public Nullable<int> Customer_FK { get; set; }
        public string CustomerIDLabel { get; set; }
        public string CustomerID { get; set; }
        public string PackageTypeIDLabel { get; set; }
        public string PackageType { get; set; }
        public string OtherLabelID { get; set; }
        public string OtherLabel { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public string ValueDate { get; set; }
        public string ValueTime { get; set; }
        public Nullable<int> Merchant_FK { get; set; }
    }
}
