//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GlobalLending.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoanEmployeeInfo
    {
        public int ID { get; set; }
        public int Loan_Fk { get; set; }
        public string EmployeeName { get; set; }
        public string OfficeAddress { get; set; }
        public string EmploymentStatus { get; set; }
        public string EmploymentDuration { get; set; }
    
        public virtual Loan Loan { get; set; }
    }
}
