//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GlobalLending.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoanBank
    {
        public int ID { get; set; }
        public Nullable<int> Loan_Fk { get; set; }
        public string BankName { get; set; }
        public string AccountName { get; set; }
        public string AccountNumber { get; set; }
        public string Bvn { get; set; }
    
        public virtual Loan Loan { get; set; }
        public virtual Loan Loan1 { get; set; }
    }
}
