//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GlobalLending.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PageAuthentication
    {
        public int id { get; set; }
        public string PageName { get; set; }
        public Nullable<int> RoleId { get; set; }
        public string isVissible { get; set; }
    
        public virtual Role Role { get; set; }
    }
}
