//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GloballendingViews.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentLog
    {
        public int ID { get; set; }
        public string CustomerName { get; set; }
        public string CustomerID { get; set; }
        public Nullable<double> Amount { get; set; }
        public Nullable<double> ServiceCharge { get; set; }
        public string ReferenceNumber { get; set; }
        public string PaymentReference { get; set; }
        public string TrxToken { get; set; }
        public string CustomerEmail { get; set; }
        public string CustomerPhoneNumber { get; set; }
        public Nullable<System.DateTime> TrnDate { get; set; }
        public string ValueDate { get; set; }
        public string ValueTime { get; set; }
        public string ResponseCode { get; set; }
        public string ResponseDescription { get; set; }
    }
}
