//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class AgentComission
    {
        public int ID { get; set; }
        public int Agent_UserFK { get; set; }
        public int Merchant_FK { get; set; }
        public Nullable<double> VendingComission { get; set; }
        public Nullable<double> LendingComission { get; set; }
        public Nullable<int> IsVisible { get; set; }
        public string Audit { get; set; }
        public Nullable<System.DateTime> trnDate { get; set; }
        public string ValueDate { get; set; }
    }
}
