//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class AgentAccount
    {
        public int ID { get; set; }
        public Nullable<int> AgentUser_FK { get; set; }
        public Nullable<double> Debit { get; set; }
        public Nullable<double> Credit { get; set; }
        public string ReferenceNumber { get; set; }
        public string Narration { get; set; }
        public Nullable<System.DateTime> TranxDate { get; set; }
        public string ValueDate { get; set; }
        public string ValueTime { get; set; }
    }
}
