//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class AgentUser
    {
        public int ID { get; set; }
        public Nullable<int> User_FK { get; set; }
        public string AgentID { get; set; }
        public string AgentKey { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public string ValueDate { get; set; }
        public string ValueTime { get; set; }
        public string EmailAddress { get; set; }
        public string PhoneNumber { get; set; }
        public string ContactPerson { get; set; }
        public string ContactAddress { get; set; }
        public string ReferralCode { get; set; }
        public string tokenVal { get; set; }
        public Nullable<double> myTokenTime { get; set; }
        public Nullable<int> PartnerFk { get; set; }
    }
}
