//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerLedger
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> trnDate { get; set; }
        public string RefrenceNumber { get; set; }
        public Nullable<double> Debit { get; set; }
        public Nullable<double> Credit { get; set; }
        public Nullable<int> Customer_FK { get; set; }
        public Nullable<int> Merchant_FK { get; set; }
        public string Channel { get; set; }
    }
}
