//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class EligibleCustomer
    {
        public int Id { get; set; }
        public Nullable<int> Merchant_Fk { get; set; }
        public string CustomerID { get; set; }
        public string CustomerIDLabel { get; set; }
        public Nullable<int> CreditLimitType { get; set; }
        public Nullable<double> CreditLimit { get; set; }
        public Nullable<double> ARPUBandMin { get; set; }
        public Nullable<double> ARPUBandMax { get; set; }
        public string CustomerMessage { get; set; }
        public string BusinessDistrict { get; set; }
    }
}
