//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Loan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Loan()
        {
            this.LoanBanks = new HashSet<LoanBank>();
            this.LoanBanks1 = new HashSet<LoanBank>();
            this.LoanEmployeeInfoes = new HashSet<LoanEmployeeInfo>();
            this.LoanSocials = new HashSet<LoanSocial>();
        }
    
        public int ID { get; set; }
        public Nullable<int> Customer_Fk { get; set; }
        public string Firstname { get; set; }
        public string Lastname { get; set; }
        public Nullable<decimal> LoanAmount { get; set; }
        public Nullable<int> Tenor { get; set; }
        public Nullable<int> InterestRate { get; set; }
        public Nullable<decimal> MonthlySalary { get; set; }
        public string PrimaryPhoneNumber { get; set; }
        public string SecondaryPhoneNumber { get; set; }
        public string DateOfBirth { get; set; }
        public string ContactAddress { get; set; }
        public string PrimaryEmailAddress { get; set; }
        public string SecondaryEmailAddress { get; set; }
        public Nullable<decimal> OtherIncome { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LoanBank> LoanBanks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LoanBank> LoanBanks1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LoanEmployeeInfo> LoanEmployeeInfoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LoanSocial> LoanSocials { get; set; }
    }
}
