//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Merchant
    {
        public int ID { get; set; }
        public Nullable<int> MerchantID { get; set; }
        public string MarchantName { get; set; }
        public string MarchantCode { get; set; }
        public string ContactName { get; set; }
        public string ContactEmail { get; set; }
        public string ContactPhoneNumber { get; set; }
        public Nullable<double> ServiceCharge { get; set; }
        public Nullable<double> CommisionVal { get; set; }
        public Nullable<int> MerchantServiceType_FK { get; set; }
        public Nullable<int> IsVisible { get; set; }
    }
}
