//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pag
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pag()
        {
            this.Pag1 = new HashSet<Pag>();
        }
    
        public int id { get; set; }
        public string PageName { get; set; }
        public string PageUrl { get; set; }
        public Nullable<int> RoleId { get; set; }
        public Nullable<int> isvisible { get; set; }
        public Nullable<int> pageHeader { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pag> Pag1 { get; set; }
        public virtual Pag Pag2 { get; set; }
    }
}
