//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class StartimeServiceList
    {
        public int id { get; set; }
        public int StartimeServiceFk { get; set; }
        public int StartimeBouquetFk { get; set; }
        public Nullable<double> Amount { get; set; }
        public string PackageDescription { get; set; }
        public Nullable<int> isVissible { get; set; }
        public Nullable<int> FrequencyType { get; set; }
        public Nullable<int> PaymentPlanId { get; set; }
    }
}
