//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubAgentTransaction
    {
        public int ID { get; set; }
        public Nullable<int> AgentUser_FK { get; set; }
        public Nullable<System.DateTime> trnDate { get; set; }
        public string RefNumber { get; set; }
        public string CustomerID { get; set; }
        public string Narration { get; set; }
        public Nullable<double> Debit { get; set; }
        public Nullable<double> Credit { get; set; }
        public Nullable<int> IsVisible { get; set; }
    }
}
